import 'package:vexana/vexana.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
 class TokenModel extends INetworkModel<TokenModel> {
/*
{
  "token": "QpwL5tke4Pnpja7X4"
} 
*/

  String? token;

  TokenModel({
    this.token,
  });
  TokenModel.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    return data;
  }
  
  @override
  TokenModel fromJson(Map<String, dynamic> json) {
    // TODO: implement fromJson
    throw UnimplementedError();
  }
  

  
}
